### ISSUE TITLE
pkg.author.split is not a function

### ISSUE THREAD

**Issue by jtrumbull** [cjpatoilo/banner-cli#3]
The `author` field, in your package.json, can be represented as an object or a shorthand string. From  [package.json specs](https://docs.npmjs.com/files/package.json):

> The "author" is one person. "contributors" is an array of people. A "person" is an object with a "name" field and optionally "url" and "email", like this:
```javascript
{
    "name"  : "Barney Rubble",
    "email" : "b@rubble.com",
    "url"   : "http://barnyrubble.tumblr.com/"
}
```

> Or you can shorten that all into a single string, and npm will parse it for you:

`"Barney Rubble <b@rubble.com> (http://barnyrubble.tumblr.com/)"`

<hr />

Presently, the module assumes you are using the shorthand string format ([@ Line 11](https://github.com/cjpatoilo/banner-cli/blob/master/index.js#L11)), and will throw an error otherwise.

```javascript
options.author = options.author || pkg.author.split('<')[0].trim() || ''
```
```
TypeError: pkg.author.split is not a function
    at banner (X:\path\to\AppData\Roaming\npm\node_modules\banner-cli\index.js:11:48)
    at Object.<anonymous> (X:\path\to\AppData\Roaming\npm\node_modules\banner-cli\cli.js:89:2)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

**Comment by cjpatoilo** [comment]
@jtrumbull Good call 🚀

Please, can you review it?

- [Add support to author field can be object or string](https://github.com/cjpatoilo/banner-cli/compare/v0.13.0...feature/v0.14.0)
